### LazyPredict

In [1]:
%pip install lazypredict

Collecting lazypredict
  Downloading lazypredict-0.3.0-py3-none-any.whl (71 kB)
     -------------------------------------- 71.0/71.0 kB 646.5 kB/s eta 0:00:00
Requirement already satisfied: click in c:\users\dell\mlenv\lib\site-packages (from lazypredict) (8.4.2)
Requirement already satisfied: scikit-learn>=1.0 in c:\users\dell\mlenv\lib\site-packages (from lazypredict) (1.9.0)
Requirement already satisfied: pandas>=1.3 in c:\users\dell\mlenv\lib\site-packages (from lazypredict) (2.3.3)
Requirement already satisfied: tqdm>=4.0 in c:\users\dell\mlenv\lib\site-packages (from lazypredict) (4.68.3)
Requirement already satisfied: joblib>=1.0 in c:\users\dell\mlenv\lib\site-packages (from lazypredict) (1.5.3)
Requirement already satisfied: numpy>=1.21 in c:\users\dell\mlenv\lib\site-packages (from lazypredict) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dell\mlenv\lib\site-packages (from pandas>=1.3->lazypredict) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\dell\mlenv\lib\site-packages (from pandas>=1.3->lazypredict) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\dell\mlenv\lib\site-packages (from pandas>=1.3->lazypredict) (2026.2)
Requirement already satisfied: scipy>=1.10.0 in c:\users\dell\mlenv\lib\site-packages (from scikit-learn>=1.0->lazypredict) (1.16.3)
Requirement already satisfied: narwhals>=2.0.1 in c:\users\dell\mlenv\lib\site-packages (from scikit-learn>=1.0->lazypredict) (2.23.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\users\dell\mlenv\lib\site-packages (from scikit-learn>=1.0->lazypredict) (3.6.0)
Requirement already satisfied: colorama in c:\users\dell\mlenv\lib\site-packages (from tqdm>=4.0->lazypredict) (0.4.6)
Requirement already satisfied: six>=1.5 in c:\users\dell\mlenv\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.3->lazypredict) (1.17.0)
Installing collected packages: lazypredict
Successfully installed lazypredict-0.3.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import lazypredict
from lazypredict.Supervised import LazyClassifier
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split

data = load_breast_cancer()
X = data.data
y= data.target

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=.30,random_state =123)

clf = LazyClassifier(verbose=0,ignore_warnings=True, custom_metric=None)
models,predictions = clf.fit(X_train, X_test, y_train, y_test)

print(models)

                             Accuracy  Balanced Accuracy   ROC AUC  F1 Score  \
Model
SGDClassifier                0.994152           0.992647  0.994860  0.994145
LogisticRegression           0.994152           0.992647  0.994860  0.994145
LinearSVC                    0.988304           0.985294  0.990577  0.988273
Perceptron                   0.988304           0.985294  0.989863  0.988273
ExtraTreesClassifier         0.982456           0.980440  0.987079  0.982434
RandomForestClassifier       0.982456           0.980440  0.992005  0.982434
SVC                          0.982456           0.980440  0.994717  0.982434
RidgeClassifier              0.982456           0.977941  0.994717  0.982384
AdaBoostClassifier           0.976608           0.975585  0.995717  0.976608
KNeighborsClassifier         0.976608           0.973087  0.990363  0.976546
LinearDiscriminantAnalysis   0.976608           0.970588  0.994575  0.976477
CalibratedClassifierCV       0.976608           0.970588  0.993147  0.976477
BernoulliNB                  0.964912           0.963378  0.994432  0.964912
RidgeClassifierCV            0.970760           0.963235  0.994003  0.970549
PassiveAggressiveClassifier  0.959064           0.961022  0.983438  0.959204
DecisionTreeClassifier       0.964912           0.960879  0.960879  0.964819
LabelSpreading               0.959064           0.956025       NaN  0.959012
LabelPropagation             0.959064           0.956025       NaN  0.959012
NuSVC                        0.964912           0.955882  0.991433  0.964599
NearestCentroid              0.964912           0.955882  0.989863  0.964599
BaggingClassifier            0.953216           0.953669  0.987507  0.953326
ExtraTreeClassifier          0.959064           0.953527  0.953527  0.958896
GaussianNB                   0.959064           0.951028  0.995717  0.958768
DummyClassifier              0.602339           0.500000  0.500000  0.452854

                             Precision    Recall  Time Taken
Model
SGDClassifier                 0.994208  0.994152    0.058652
LogisticRegression            0.994208  0.994152    0.035704
LinearSVC                     0.988527  0.988304    0.034988
Perceptron                    0.988527  0.988304    0.031827
ExtraTreesClassifier          0.982481  0.982456    0.550467
RandomForestClassifier        0.982481  0.982456    0.357320
SVC                           0.982481  0.982456    0.055316
RidgeClassifier               0.982953  0.982456    0.026060
AdaBoostClassifier            0.976608  0.976608    0.263069
KNeighborsClassifier          0.976765  0.976608    2.249578
LinearDiscriminantAnalysis    0.977483  0.976608    0.034101
CalibratedClassifierCV        0.977483  0.976608    0.127925
BernoulliNB                   0.964912  0.964912    0.024753
RidgeClassifierCV             0.972114  0.970760    0.041593
PassiveAggressiveClassifier   0.959949  0.959064    0.044342
DecisionTreeClassifier        0.965003  0.964912    0.064445
LabelSpreading                0.959027  0.959064    0.051120
LabelPropagation              0.959027  0.959064    0.041532
NuSVC                         0.966844  0.964912    0.041307
NearestCentroid               0.966844  0.964912    0.027072
BaggingClassifier             0.953704  0.953216    0.083306
ExtraTreeClassifier           0.959352  0.959064    0.117222
GaussianNB                    0.960225  0.959064    0.028600
DummyClassifier               0.362812  0.602339    0.070636

In [3]:
models

,Accuracy,Balanced Accuracy,ROC AUC,F1 Score,Precision,Recall,Time Taken
Model,,,,,,,
SGDClassifier,0.994152,0.992647,0.994860,0.994145,0.994208,0.994152,0.058652
LogisticRegression,0.994152,0.992647,0.994860,0.994145,0.994208,0.994152,0.035704
LinearSVC,0.988304,0.985294,0.990577,0.988273,0.988527,0.988304,0.034988
Perceptron,0.988304,0.985294,0.989863,0.988273,0.988527,0.988304,0.031827
ExtraTreesClassifier,0.982456,0.980440,0.987079,0.982434,0.982481,0.982456,0.550467
RandomForestClassifier,0.982456,0.980440,0.992005,0.982434,0.982481,0.982456,0.357320
SVC,0.982456,0.980440,0.994717,0.982434,0.982481,0.982456,0.055316
RidgeClassifier,0.982456,0.977941,0.994717,0.982384,0.982953,0.982456,0.026060
AdaBoostClassifier,0.976608,0.975585,0.995717,0.976608,0.976608,0.976608,0.263069
KNeighborsClassifier,0.976608,0.973087,0.990363,0.976546,0.976765,0.976608,2.249578
LinearDiscriminantAnalysis,0.976608,0.970588,0.994575,0.976477,0.977483,0.976608,0.034101
CalibratedClassifierCV,0.976608,0.970588,0.993147,0.976477,0.977483,0.976608,0.127925
BernoulliNB,0.964912,0.963378,0.994432,0.964912,0.964912,0.964912,0.024753
RidgeClassifierCV,0.970760,0.963235,0.994003,0.970549,0.972114,0.970760,0.041593
PassiveAggressiveClassifier,0.959064,0.961022,0.983438,0.959204,0.959949,0.959064,0.044342
DecisionTreeClassifier,0.964912,0.960879,0.960879,0.964819,0.965003,0.964912,0.064445
LabelSpreading,0.959064,0.956025,NaN,0.959012,0.959027,0.959064,0.051120
LabelPropagation,0.959064,0.956025,NaN,0.959012,0.959027,0.959064,0.041532
NuSVC,0.964912,0.955882,0.991433,0.964599,0.966844,0.964912,0.041307
NearestCentroid,0.964912,0.955882,0.989863,0.964599,0.966844,0.964912,0.027072
BaggingClassifier,0.953216,0.953669,0.987507,0.953326,0.953704,0.953216,0.083306
ExtraTreeClassifier,0.959064,0.953527,0.953527,0.958896,0.959352,0.959064,0.117222
GaussianNB,0.959064,0.951028,0.995717,0.958768,0.960225,0.959064,0.028600
DummyClassifier,0.602339,0.500000,0.500000,0.452854,0.362812,0.602339,0.070636

In [4]:
from lazypredict.Supervised import LazyRegressor
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split

# Load California Housing Dataset
data = load_breast_cancer()

# Features and Target
X = data.data
y = data.target

# Split the dataset into Training and Testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.10,
    random_state=13
)

# Create LazyRegressor object
reg = LazyRegressor(
    verbose=0,
    ignore_warnings=True,
    custom_metric=None
)

# Train all Regression Models
models, predictions = reg.fit(
    X_train,
    X_test,
    y_train,
    y_test
)

# Display performance of all models
print(models)

                               Adjusted R-Squared    R-Squared       RMSE  \
Model
KNeighborsRegressor                      0.720184     0.870085   0.167542
NuSVR                                    0.634104     0.830120   0.191587
SVR                                      0.630439     0.828418   0.192544
AdaBoostRegressor                        0.612762     0.820211   0.197095
MLPRegressor                             0.559707     0.795578   0.210164
ExtraTreesRegressor                      0.523613     0.778821   0.218608
LassoLarsCV                              0.416512     0.729095   0.241937
LassoCV                                  0.416304     0.728998   0.241980
ElasticNetCV                             0.415413     0.728585   0.242165
BayesianRidge                            0.414685     0.728247   0.242315
LassoLarsIC                              0.412935     0.727434   0.242677
TransformedTargetRegressor               0.402695     0.722680   0.244785
LinearRegression                         0.402695     0.722680   0.244785
Ridge                                    0.399565     0.721227   0.245425
RidgeCV                                  0.399565     0.721227   0.245425
OrthogonalMatchingPursuitCV              0.398070     0.720532   0.245731
SGDRegressor                             0.396475     0.719792   0.246056
LinearSVR                                0.378734     0.711555   0.249646
HuberRegressor                           0.368469     0.706789   0.251700
BaggingRegressor                         0.338935     0.693077   0.257519
HistGradientBoostingRegressor            0.335898     0.691667   0.258109
RandomForestRegressor                    0.314154     0.681571   0.262301
OrthogonalMatchingPursuit                0.313368     0.681207   0.262451
TweedieRegressor                         0.305671     0.677633   0.263918
GradientBoostingRegressor                0.202372     0.629673   0.282870
GaussianProcessRegressor                 0.176421     0.617624   0.287435
PoissonRegressor                         0.110520     0.587027   0.298713
DecisionTreeRegressor                   -0.049310     0.512821   0.324443
PassiveAggressiveRegressor              -0.191302     0.446896   0.345698
ExtraTreeRegressor                      -0.224195     0.431624   0.350438
LarsCV                                  -0.265906     0.412258   0.356358
ElasticNet                              -1.193558    -0.018438   0.469095
DummyRegressor                          -1.193558    -0.018438   0.469095
Lasso                                   -1.193558    -0.018438   0.469095
LassoLars                               -1.193558    -0.018438   0.469095
QuantileRegressor                       -2.147929    -0.461538   0.561951
RANSACRegressor                         -2.147929    -0.461538   0.561951
KernelRidge                             -3.832560    -1.243688   0.696266
Lars                                 -6939.918646 -3221.569371  26.387293

                               Time Taken
Model
KNeighborsRegressor              0.017535
NuSVR                            0.038013
SVR                              0.016886
AdaBoostRegressor                0.214791
MLPRegressor                     0.378240
ExtraTreesRegressor              0.217861
LassoLarsCV                      0.090810
LassoCV                          0.234270
ElasticNetCV                     0.148499
BayesianRidge                    0.016133
LassoLarsIC                      0.045058
TransformedTargetRegressor       0.049533
LinearRegression                 0.013310
Ridge                            0.008483
RidgeCV                          0.016105
OrthogonalMatchingPursuitCV      0.016724
SGDRegressor                     0.016708
LinearSVR                        0.041562
HuberRegressor                   0.040910
BaggingRegressor                 0.078298
HistGradientBoostingRegressor    0.590330
RandomForestRegressor            0.483480
OrthogonalMatchingPursuit        0.016650
TweedieRegressor                 0.021406
GradientBoostingRegressor        0.573615
GaussianProcessRegressor         0.900220
PoissonRegressor                 0.016262
DecisionTreeRegressor            0.010432
PassiveAggressiveRegressor       0.008557
ExtraTreeRegressor               0.004527
LarsCV                           0.039041
ElasticNet                       0.020976
DummyRegressor                   0.016734
Lasso                            0.010036
LassoLars                        0.017118
QuantileRegressor                0.076525
RANSACRegressor                  0.132070
KernelRidge                      0.024523
Lars                             0.017497

In [5]:
models

,Adjusted R-Squared,R-Squared,RMSE,Time Taken
Model,,,,
KNeighborsRegressor,0.720184,0.870085,0.167542,0.017535
NuSVR,0.634104,0.830120,0.191587,0.038013
SVR,0.630439,0.828418,0.192544,0.016886
AdaBoostRegressor,0.612762,0.820211,0.197095,0.214791
MLPRegressor,0.559707,0.795578,0.210164,0.378240
ExtraTreesRegressor,0.523613,0.778821,0.218608,0.217861
LassoLarsCV,0.416512,0.729095,0.241937,0.090810
LassoCV,0.416304,0.728998,0.241980,0.234270
ElasticNetCV,0.415413,0.728585,0.242165,0.148499
BayesianRidge,0.414685,0.728247,0.242315,0.016133
LassoLarsIC,0.412935,0.727434,0.242677,0.045058
TransformedTargetRegressor,0.402695,0.722680,0.244785,0.049533
LinearRegression,0.402695,0.722680,0.244785,0.013310
Ridge,0.399565,0.721227,0.245425,0.008483
RidgeCV,0.399565,0.721227,0.245425,0.016105
OrthogonalMatchingPursuitCV,0.398070,0.720532,0.245731,0.016724
SGDRegressor,0.396475,0.719792,0.246056,0.016708
LinearSVR,0.378734,0.711555,0.249646,0.041562
HuberRegressor,0.368469,0.706789,0.251700,0.040910
BaggingRegressor,0.338935,0.693077,0.257519,0.078298
HistGradientBoostingRegressor,0.335898,0.691667,0.258109,0.590330
RandomForestRegressor,0.314154,0.681571,0.262301,0.483480
OrthogonalMatchingPursuit,0.313368,0.681207,0.262451,0.016650
TweedieRegressor,0.305671,0.677633,0.263918,0.021406
GradientBoostingRegressor,0.202372,0.629673,0.282870,0.573615
GaussianProcessRegressor,0.176421,0.617624,0.287435,0.900220
PoissonRegressor,0.110520,0.587027,0.298713,0.016262
DecisionTreeRegressor,-0.049310,0.512821,0.324443,0.010432
PassiveAggressiveRegressor,-0.191302,0.446896,0.345698,0.008557
ExtraTreeRegressor,-0.224195,0.431624,0.350438,0.004527
LarsCV,-0.265906,0.412258,0.356358,0.039041
ElasticNet,-1.193558,-0.018438,0.469095,0.020976
DummyRegressor,-1.193558,-0.018438,0.469095,0.016734
Lasso,-1.193558,-0.018438,0.469095,0.010036
LassoLars,-1.193558,-0.018438,0.469095,0.017118
QuantileRegressor,-2.147929,-0.461538,0.561951,0.076525
RANSACRegressor,-2.147929,-0.461538,0.561951,0.132070
KernelRidge,-3.832560,-1.243688,0.696266,0.024523
Lars,-6939.918646,-3221.569371,26.387293,0.017497

In [6]:
import seaborn as sns

In [7]:
df=sns.load_dataset('titanic')

In [8]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [9]:
X=df.drop('survived',axis=1)
y=df.iloc[:,0]

In [10]:
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: survived, Length: 891, dtype: int64

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=.25,random_state =123)

In [12]:
clf = LazyClassifier(verbose=0, ignore_warnings=False, custom_metric=None)
models,predictions = clf.fit(X_train, X_test, y_train, y_test)

CategoricalNB model failed to execute: Negative values in data passed to CategoricalNB (input X).
FixedThresholdClassifier model failed to execute: FixedThresholdClassifier.__init__() missing 1 required positional argument: 'estimator'
c:\Users\Dell\mlenv\Lib\site-packages\sklearn\neighbors\_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
c:\Users\Dell\mlenv\Lib\site-packages\sklearn\utils\deprecation.py:71: FutureWarning: Class PassiveAggressiveClassifier is deprecated; this is deprecated in version 1.8 and will be removed in 1.10. Use `SGDClassifier(loss='hinge', penalty=None, learning_rate='pa1', eta0=1.0)` instead.
  warnings.warn(msg, category=FutureWarning)
QuadraticDiscriminantAnalysis model failed to execute: The covariance matrix of class 0 is not full rank. Increase the value of `reg_param` to reduce the collinearity.
SelfTrainingClassifier model failed to execute: The 'estimator' parameter of SelfTrainingClassifier must be an object implementing 'fit'. Got None instead.
StackingClassifier model failed to execute: StackingClassifier.__init__() missing 1 required positional argument: 'estimators'
TunedThresholdClassifierCV model failed to execute: TunedThresholdClassifierCV.__init__() missing 1 required positional argument: 'estimator'

In [13]:
print(models)

                             Accuracy  Balanced Accuracy   ROC AUC  F1 Score  \
Model
AdaBoostClassifier           1.000000           1.000000  1.000000  1.000000
BaggingClassifier            1.000000           1.000000  1.000000  1.000000
BernoulliNB                  1.000000           1.000000  1.000000  1.000000
CalibratedClassifierCV       1.000000           1.000000  1.000000  1.000000
DecisionTreeClassifier       1.000000           1.000000  1.000000  1.000000
ExtraTreeClassifier          1.000000           1.000000  1.000000  1.000000
ExtraTreesClassifier         1.000000           1.000000  1.000000  1.000000
GaussianNB                   1.000000           1.000000  1.000000  1.000000
SVC                          1.000000           1.000000  1.000000  1.000000
LinearSVC                    1.000000           1.000000  1.000000  1.000000
LogisticRegression           1.000000           1.000000  1.000000  1.000000
SGDClassifier                1.000000           1.000000  1.000000  1.000000
RidgeClassifier              1.000000           1.000000  1.000000  1.000000
RandomForestClassifier       1.000000           1.000000  1.000000  1.000000
Perceptron                   1.000000           1.000000  1.000000  1.000000
PassiveAggressiveClassifier  1.000000           1.000000  1.000000  1.000000
RidgeClassifierCV            1.000000           1.000000  1.000000  1.000000
NuSVC                        0.986547           0.984498  0.999400  0.986531
LabelSpreading               0.968610           0.967754  0.988181  0.968646
LabelPropagation             0.968610           0.967754  0.990922  0.968646
KNeighborsClassifier         0.955157           0.947542  0.991264  0.954928
LinearDiscriminantAnalysis   0.838565           0.816333  0.864894  0.836259
NearestCentroid              0.816143           0.814834  0.912641  0.817742
DummyClassifier              0.623318           0.500000  0.500000  0.478681

                             Precision    Recall  Time Taken
Model
AdaBoostClassifier            1.000000  1.000000    0.069114
BaggingClassifier             1.000000  1.000000    0.077485
BernoulliNB                   1.000000  1.000000    0.064211
CalibratedClassifierCV        1.000000  1.000000    0.138144
DecisionTreeClassifier        1.000000  1.000000    0.074238
ExtraTreeClassifier           1.000000  1.000000    0.058736
ExtraTreesClassifier          1.000000  1.000000    0.307921
GaussianNB                    1.000000  1.000000    0.076420
SVC                           1.000000  1.000000    0.066693
LinearSVC                     1.000000  1.000000    0.084471
LogisticRegression            1.000000  1.000000    0.055658
SGDClassifier                 1.000000  1.000000    0.075499
RidgeClassifier               1.000000  1.000000    0.062825
RandomForestClassifier        1.000000  1.000000    0.260092
Perceptron                    1.000000  1.000000    0.050140
PassiveAggressiveClassifier   1.000000  1.000000    0.058238
RidgeClassifierCV             1.000000  1.000000    0.058180
NuSVC                         0.986557  0.986547    0.074066
LabelSpreading                0.968723  0.968610    0.066721
LabelPropagation              0.968723  0.968610    0.058183
KNeighborsClassifier          0.955362  0.955157    0.115154
LinearDiscriminantAnalysis    0.837609  0.838565    0.059975
NearestCentroid               0.822025  0.816143    0.075900
DummyClassifier               0.388526  0.623318    0.066242

In [14]:
models

,Accuracy,Balanced Accuracy,ROC AUC,F1 Score,Precision,Recall,Time Taken
Model,,,,,,,
AdaBoostClassifier,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.069114
BaggingClassifier,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.077485
BernoulliNB,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.064211
CalibratedClassifierCV,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.138144
DecisionTreeClassifier,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.074238
ExtraTreeClassifier,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.058736
ExtraTreesClassifier,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.307921
GaussianNB,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.076420
SVC,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.066693
LinearSVC,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.084471
LogisticRegression,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.055658
SGDClassifier,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.075499
RidgeClassifier,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.062825
RandomForestClassifier,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.260092
Perceptron,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.050140
PassiveAggressiveClassifier,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.058238
RidgeClassifierCV,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.058180
NuSVC,0.986547,0.984498,0.999400,0.986531,0.986557,0.986547,0.074066
LabelSpreading,0.968610,0.967754,0.988181,0.968646,0.968723,0.968610,0.066721
LabelPropagation,0.968610,0.967754,0.990922,0.968646,0.968723,0.968610,0.058183
KNeighborsClassifier,0.955157,0.947542,0.991264,0.954928,0.955362,0.955157,0.115154
LinearDiscriminantAnalysis,0.838565,0.816333,0.864894,0.836259,0.837609,0.838565,0.059975
NearestCentroid,0.816143,0.814834,0.912641,0.817742,0.822025,0.816143,0.075900
DummyClassifier,0.623318,0.500000,0.500000,0.478681,0.388526,0.623318,0.066242